// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1a2lLsPNN_68YWKiEqkiO57dQtzTFDrc',
    appId: '1:792093820716:web:887bdf92451578d2574e89',
    messagingSenderId: '792093820716',
    projectId: 'flr-blockchains',
    authDomain: 'flr-blockchains.firebaseapp.com',
    storageBucket: 'flr-blockchains.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVtk4A8Ef0BjwAmMZMXrSCrujkwitXXJo',
    appId: '1:792093820716:android:9e2bc3c4b7448732574e89',
    messagingSenderId: '792093820716',
    projectId: 'flr-blockchains',
    storageBucket: 'flr-blockchains.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZonee573Scg04AogaLZc-3Xzr8pTeqVI',
    appId: '1:792093820716:ios:094ee735d14be922574e89',
    messagingSenderId: '792093820716',
    projectId: 'flr-blockchains',
    storageBucket: 'flr-blockchains.appspot.com',
    iosBundleId: 'com.example.flare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZonee573Scg04AogaLZc-3Xzr8pTeqVI',
    appId: '1:792093820716:ios:397aa4d5796c3873574e89',
    messagingSenderId: '792093820716',
    projectId: 'flr-blockchains',
    storageBucket: 'flr-blockchains.appspot.com',
    iosBundleId: 'com.example.flare.RunnerTests',
  );
}
